name: TaterlandHardcore
version: '${version}'
main: dev.neuralnexus.taterlandhardcore.bukkit.BukkitTaterlandHardcorePlugin
author: p0t4t0sandwich
description: Plugin used by the Taterland Hardcore server.
folia-supported: true
commands:
  untempban:
    description: Unbans a player from TempBanDeath.
    usage: /<command> <player>
    permission: taterlandhardcore.untempban
