version: 1
tempban:
  # Tempban time in seconds -- default: 22 hours (79200 seconds)
  time: 79200
  # Tempban message -- default: "You have been temporarily banned for x days."
  message: "§cYou have been temporarily banned for one day."
